ALTER TABLE "document_signers"
ADD COLUMN "visiblePage" INTEGER,
ADD COLUMN "visibleX" DOUBLE PRECISION,
ADD COLUMN "visibleY" DOUBLE PRECISION,
ADD COLUMN "visibleWidth" DOUBLE PRECISION,
ADD COLUMN "visibleHeight" DOUBLE PRECISION;
