ALTER TYPE "Role" RENAME TO "Role_old";

CREATE TYPE "Role" AS ENUM (
  'SUPERADMIN',
  'JURUSAN',
  'PRODI',
  'ADMIN_PRODI',
  'PEGAWAI',
  'MAHASISWA'
);

ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT;

ALTER TABLE "users"
ALTER COLUMN "role" TYPE "Role"
USING (
  CASE "role"::text
    WHEN 'ADMIN' THEN 'SUPERADMIN'
    WHEN 'VERIFIER' THEN 'ADMIN_PRODI'
    WHEN 'MEMBER' THEN 'MAHASISWA'
    ELSE 'MAHASISWA'
  END
)::"Role";

ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'MAHASISWA';

DROP TYPE "Role_old";

ALTER TABLE "documents"
ADD COLUMN "qrCodePage" INTEGER,
ADD COLUMN "qrCodeX" DOUBLE PRECISION,
ADD COLUMN "qrCodeY" DOUBLE PRECISION,
ADD COLUMN "qrCodeWidth" DOUBLE PRECISION,
ADD COLUMN "qrCodeHeight" DOUBLE PRECISION;

ALTER TABLE "document_signers"
ADD COLUMN "declinedAt" TIMESTAMP(3),
ADD COLUMN "declineReason" TEXT;
